{
  config',
  base16,
  pkgs,
  lib,
  ...
}: let
  # TODO
  conf_scheme = config'.colorscheme;
  parsed =
    if builtins.isAttrs conf_scheme
    then conf_scheme
    else "${pkgs.base16-schemes}/share/themes/${conf_scheme}.yaml";
  base16Lib = pkgs.callPackage base16.lib {};
  scheme = base16Lib.mkSchemeAttrs parsed;
in {
  vim = {
    theme = {
    enable = true;
    name = "base16";
    base16-colors = {
      base00 = scheme.base00;
      base01 = scheme.base01;
      base02 = scheme.base02;
      base03 = scheme.base03;
      base04 = scheme.base04;
      base05 = scheme.base05;
      base06 = scheme.base06;
      base07 = scheme.base07;
      base08 = scheme.base08;
      base09 = scheme.base09;
      base0A = scheme.base0A;
      base0B = scheme.base0B;
      base0C = scheme.base0C;
      base0D = scheme.base0D;
      base0E = scheme.base0E;
      base0F = scheme.base0F;
    };
  };
  luaConfigRC.dashvim = /*lua*/ ''
      local function clamp(component)
              return math.min(math.max(component, 0), 255)
      end
      function change_color(col, amt)
              local num = tonumber(col, 16)
              local r = math.floor(num / 0x10000) + amt
              local g = (math.floor(num / 0x100) % 0x100) + amt
              local b = (num % 0x100) + amt
              return string.format("%X", clamp(r) * 0x10000 + clamp(g) * 0x100 + clamp(b))
      end
      
      function fix_theme()
              mantle = change_color("${scheme.base00}", 43)
              overlay0 = change_color("${scheme.base02}", 59.0118)
              overlay1 = change_color("${scheme.base03}", 58.0118)
              overlay2 = change_color("${scheme.base04}", 59.0118)
              vim.cmd("highlight  EndOfBufferxxx guifg=#${scheme.base00}")
              vim.cmd("highlight  Directoryxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  ErrorMsgxxx cterm=bold,italic gui=bold,italic guifg=#${scheme.base08}")
              vim.cmd("highlight  IncSearchxxx guifg=#${scheme.base01} guibg=#7ec9d9")
              vim.cmd("highlight  Searchxxx guifg=#${scheme.base05} guibg=#3e5768")
              vim.cmd("highlight  CurSearchxxx guifg=#${scheme.base01} guibg=#${scheme.base08}")
              vim.cmd("highlight  MoreMsgxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  ModeMsgxxx cterm=bold gui=bold guifg=#${scheme.base05}")
              vim.cmd("highlight  LineNrxxx guifg=#${scheme.base03}")
              vim.cmd("highlight  CursorLineNrxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  Questionxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  StatusLinexxx guifg=#${scheme.base05} guibg=#${scheme.base01}")
              vim.cmd("highlight  StatusLineNCxxx guifg=#${scheme.base03} guibg=#${scheme.base01}")
              vim.cmd("highlight  Titlexxx cterm=bold gui=bold guifg=#${scheme.base0D}")
              vim.cmd("highlight  Visualxxx cterm=bold gui=bold guibg=#${scheme.base03}")
              vim.cmd("highlight  WarningMsgxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  Foldedxxx guifg=#${scheme.base0D} guibg=#${scheme.base03}")
              vim.cmd("highlight  SignColumnxxx guifg=#${scheme.base03}")
              vim.cmd("highlight  SpellBadxxx cterm=undercurl gui=undercurl guisp=#${scheme.base08}")
              vim.cmd("highlight  SpellCapxxx cterm=undercurl gui=undercurl guisp=#${scheme.base0A}")
              vim.cmd("highlight  SpellRarexxx cterm=undercurl gui=undercurl guisp=#${scheme.base0B}")
              vim.cmd("highlight  SpellLocalxxx cterm=undercurl gui=undercurl guisp=#${scheme.base0D}")
              vim.cmd("highlight  PmenuSelxxx cterm=bold gui=bold guibg=#${scheme.base03}")
              vim.cmd("highlight  PmenuSbarxxx guibg=#${scheme.base03}")
              vim.cmd("highlight  TabLinexxx guifg=#${scheme.base03} guibg=#${scheme.base01}")
              vim.cmd("highlight  TabLineSelxxx guifg=#${scheme.base0B} guibg=#${scheme.base03}")
              vim.cmd("highlight  CursorColumnxxx guibg=#${scheme.base01}")
              vim.cmd("highlight  ColorColumnxxx guibg=#${scheme.base02}")
              vim.cmd("highlight  QuickFixLinexxx cterm=bold gui=bold guibg=#${scheme.base03}")
              vim.cmd("highlight  Whitespacexxx guifg=#${scheme.base03}")
              vim.cmd("highlight  NormalNCxxx guifg=#${scheme.base05} guibg=#${scheme.base00}")
              vim.cmd("highlight  NormalFloatxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  WinBarxxx guifg=#${scheme.base06}")
              vim.cmd("highlight  Cursorxxx guifg=#${scheme.base00} guibg=#${scheme.base05}")
              vim.cmd("highlight  lCursorxxx guifg=#${scheme.base00} guibg=#${scheme.base05}")
              vim.cmd("highlight  CursorIMxxx guifg=#${scheme.base00} guibg=#${scheme.base05}")
              vim.cmd("highlight  Substitutexxx guifg=#f5c2e8 guibg=#${scheme.base03}")
              vim.cmd("highlight  VisualNOSxxx cterm=bold gui=bold guibg=#${scheme.base03}")
              vim.cmd("highlight  Normalxxx guifg=#${scheme.base05} guibg=#${scheme.base00}")
              vim.cmd("highlight  Characterxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  Constantxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  Numberxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  Booleanxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  Conditionalxxx cterm=italic gui=italic guifg=#${scheme.base0E}")
              vim.cmd("highlight  Statementxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  Repeatxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  Keywordxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  Exceptionxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  Includexxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  Macroxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  StorageClassxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  Typexxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  Structurexxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  Tagxxx cterm=bold gui=bold guifg=#${scheme.base07}")
              vim.cmd("highlight  LspReferenceReadxxx guibg=#${scheme.base03}")
              vim.cmd("highlight  LspReferenceTextxxx guibg=#${scheme.base03}")
              vim.cmd("highlight  LspReferenceWritexxx guibg=#${scheme.base03}")
              vim.cmd("highlight  LspSignatureActiveParameterxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  DiagnosticFloatingErrorxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  DiagnosticErrorxxx cterm=italic gui=italic guifg=#${scheme.base08}")
              vim.cmd("highlight  DiagnosticFloatingWarnxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  DiagnosticWarnxxx cterm=italic gui=italic guifg=#${scheme.base0A}")
              vim.cmd("highlight  DiagnosticFloatingHintxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  DiagnosticHintxxx cterm=italic gui=italic guifg=#${scheme.base0C}")
              vim.cmd("highlight  DiagnosticFloatingOkxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  DiagnosticOkxxx cterm=italic gui=italic guifg=#${scheme.base0B}")
              vim.cmd("highlight  DiagnosticVirtualTextErrorxxx cterm=italic gui=italic guifg=#${scheme.base08} guibg=#32283b")
              vim.cmd("highlight  DiagnosticVirtualTextWarnxxx cterm=italic gui=italic guifg=#${scheme.base0A} guibg=#33313b")
              vim.cmd("highlight  DiagnosticVirtualTextHintxxx cterm=italic gui=italic guifg=#${scheme.base0C} guibg=#29313f")
              vim.cmd("highlight  DiagnosticVirtualTextOkxxx cterm=italic gui=italic guifg=#${scheme.base0B} guibg=#29313f")
              vim.cmd("highlight  DiagnosticSignErrorxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  DiagnosticSignWarnxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  DiagnosticSignHintxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  DiagnosticSignOkxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  @variablexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  @variable.builtinxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  @constant.builtinxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  @modulexxx cterm=italic gui=italic guifg=#${scheme.base07}")
              vim.cmd("highlight  Stringxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  @string.regexpxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  @string.special.urlxxx cterm=underline,italic gui=underline,italic guifg=#${scheme.base06}")
              vim.cmd("highlight  @type.builtinxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  @propertyxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  Identifierxxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  Functionxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  @function.builtinxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  @comment.errorxxx guifg=#${scheme.base00} guibg=#${scheme.base08}")
              vim.cmd("highlight  @comment.warningxxx guifg=#${scheme.base00} guibg=#${scheme.base0A}")
              vim.cmd("highlight  @comment.notexxx guifg=#${scheme.base00} guibg=#${scheme.base0D}")
              vim.cmd("highlight  @comment.todoxxx guifg=#${scheme.base00} guibg=#${scheme.base0F}")
              vim.cmd("highlight  Todoxxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0F}")
              vim.cmd("highlight  @markupxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  @markup.strikethroughxxx cterm=strikethrough gui=strikethrough guifg=#${scheme.base05}")
              vim.cmd("highlight  @markup.headingxxx cterm=bold gui=bold guifg=#${scheme.base0D}")
              vim.cmd("highlight  @tagxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  @lsp.type.interfacexxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  MatchParenxxx cterm=bold gui=bold guifg=#${scheme.base09} guibg=#${scheme.base03}")
              vim.cmd("highlight  Errorxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  DiagnosticUnderlineErrorxxx cterm=underline gui=underline guisp=#${scheme.base08}")
              vim.cmd("highlight  DiagnosticUnderlineWarnxxx cterm=underline gui=underline guisp=#${scheme.base0A}")
              vim.cmd("highlight  DiagnosticUnderlineHintxxx cterm=underline gui=underline guisp=#${scheme.base0C}")
              vim.cmd("highlight  DiagnosticUnderlineOkxxx cterm=underline gui=underline guisp=#${scheme.base0B}")
              vim.cmd("highlight  MiniPickBorderTextxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  MiniStarterFooterxxx cterm=italic gui=italic guifg=#${scheme.base0A}")
              vim.cmd("highlight  MiniStarterHeaderxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  MiniStarterInactivexxx cterm=italic gui=italic guifg=#${scheme.base04}")
              vim.cmd("highlight  MiniStarterItemxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  MiniStarterItemBulletxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  MiniStarterSectionxxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  MiniStarterQueryxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  MiniStatuslineDevinfoxxx guifg=#bac2df guibg=#${scheme.base03}")
              vim.cmd("highlight  MiniStatuslineFileinfoxxx guifg=#bac2df guibg=#${scheme.base03}")
              vim.cmd("highlight  MiniStatuslineFilenamexxx guifg=#${scheme.base05} guibg=#${scheme.base01}")
              vim.cmd("highlight  MiniStatuslineInactivexxx guifg=#${scheme.base0D} guibg=#${scheme.base01}")
              vim.cmd(
                      "highlight  MiniStatuslineModeCommandxxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base09}")
              vim.cmd(
              "highlight  MiniStatuslineModeInsertxxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0B}")
              vim.cmd(
              "highlight  MiniStatuslineModeNormalxxx cterm=bold gui=bold guifg=#${scheme.base01} guibg=#${scheme.base0D}")
              vim.cmd(
              "highlight  MiniStatuslineModeOtherxxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0C}")
              vim.cmd(
                      "highlight  MiniStatuslineModeReplacexxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base08}")
              vim.cmd(
              "highlight  MiniStatuslineModeVisualxxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0E}")
              vim.cmd("highlight  MiniSurroundxxx guifg=#${scheme.base03} guibg=#f5c2e8")
              vim.cmd(
                      "highlight  MiniTablineCurrentxxx cterm=bold,underline,italic gui=bold,underline,italic guifg=#${scheme.base05} guibg=#${scheme.base00} guisp=#${scheme.base08}")
              vim.cmd("highlight  MiniTablineFillxxx guibg=#${scheme.base00}")
              vim.cmd("highlight  MiniTablineHiddenxxx guifg=#${scheme.base05} guibg=#${scheme.base01}")
              vim.cmd("highlight  MiniTablineModifiedCurrentxxx cterm=bold,italic gui=bold,italic guifg=#${scheme.base08}")
              vim.cmd("highlight  MiniTablineModifiedHiddenxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  MiniTablineModifiedVisiblexxx guifg=#${scheme.base08}")
              vim.cmd("highlight  MiniTablineTabpagesectionxxx guifg=#${scheme.base03} guibg=#${scheme.base00}")
              vim.cmd("highlight  MiniTestFailxxx cterm=bold gui=bold guifg=#${scheme.base08}")
              vim.cmd("highlight  MiniTestPassxxx cterm=bold gui=bold guifg=#${scheme.base0B}")
              vim.cmd("highlight  MiniTrailspacexxx guibg=#${scheme.base08}")
              vim.cmd("highlight  @variable.memberxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  @string.documentationxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  @string.special.symbolxxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  DropBarKindArrayxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindBooleanxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  @function.macroxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  DropBarKindBreakStatementxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindCallxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindCaseStatementxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  @keyword.functionxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  DropBarKindConstantxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  @keyword.returnxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  DropBarKindConstructorxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindContinueStatementxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindDeletexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindDoStatementxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindElseStatementxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindEnumxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindEnumMemberxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindEventxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindFieldxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindFilexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindFolderxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindForStatementxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindFunctionxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindIdentifierxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindIfStatementxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindInterfacexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindKeywordxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindListxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindMacroxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindMarkdownH1xxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindMarkdownH2xxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindMarkdownH3xxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindMarkdownH4xxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindMarkdownH5xxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindMarkdownH6xxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindMethodxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindModulexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindNamespacexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindNullxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindNumberxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindObjectxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindOperatorxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DapBreakpointxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  DropBarKindPackagexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DapBreakpointRejectedxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  DropBarKindPropertyxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindReferencexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  NeogitUnstagedchangesxxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  NeogitStagedchangesxxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  diffAddedxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  NeogitRebasingxxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  NeogitNotificationWarningxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  NeogitNotificationErrorxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  NeogitGraphRedxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  NeogitGraphWhitexxx guifg=#${scheme.base00}")
              vim.cmd("highlight  NeogitGraphYellowxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  NeogitGraphGreenxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  MiniDepsTitleErrorxxx guifg=#${scheme.base00} guibg=#${scheme.base08}")
              vim.cmd("highlight  NeogitGraphPurplexxx guifg=#${scheme.base07}")
              vim.cmd("highlight  MiniDiffSignAddxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  NeogitGraphBoldRedxxx cterm=bold gui=bold guifg=#${scheme.base08}")
              vim.cmd("highlight  NeogitGraphBoldCyanxxx cterm=bold gui=bold guifg=#${scheme.base0D}")
              vim.cmd("highlight  MiniFilesFilexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  NeogitPopupSwitchKeyxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  MiniHipatternsFixmexxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base08}")
              vim.cmd("highlight  MiniHipatternsHackxxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0A}")
              vim.cmd("highlight  MiniHipatternsNotexxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#89dcec")
              vim.cmd("highlight  MiniHipatternsTodoxxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0C}")
              vim.cmd("highlight  MiniIconsBluexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NeogitSectionHeaderxxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  NeogitTagNamexxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  NeogitTagDistancexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  DropBarKindRepeatxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindScopexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindSpecifierxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindStatementxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindStringxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindStructxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindSwitchStatementxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindTypexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindTypeParameterxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindUnitxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindValuexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindVariablexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindWhileStatementxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  CmpItemKindxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemMenuxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  CmpItemAbbrMatchxxx cterm=bold gui=bold guifg=#${scheme.base05}")
              vim.cmd("highlight  CmpItemAbbrMatchFuzzyxxx cterm=bold gui=bold guifg=#${scheme.base05}")
              vim.cmd("highlight  CmpItemKindSnippetxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  CmpItemKindKeywordxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  CmpItemKindTextxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  CmpItemKindMethodxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemKindConstructorxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemKindFunctionxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemKindFolderxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemKindModulexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemKindConstantxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  CmpItemKindFieldxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  CmpItemKindPropertyxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  CmpItemKindEnumxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  CmpItemKindUnitxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  CmpItemKindClassxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  CmpItemKindVariablexxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  CmpItemKindFilexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemKindInterfacexxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  CmpItemKindColorxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  CmpItemKindReferencexxx guifg=#${scheme.base08}")
              vim.cmd("highlight  CmpItemKindEnumMemberxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  CmpItemKindStructxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemKindValuexxx guifg=#${scheme.base09}")
              vim.cmd("highlight  CmpItemKindEventxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemKindOperatorxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemKindTypeParameterxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  CmpItemKindCopilotxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  BlinkCmpLabel cterm=bold gui=bold guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKind guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindSnippet guifg=#${scheme.base0E}")
              vim.cmd("highlight  BlinkCmpKindKeyword guifg=#${scheme.base08}")
              vim.cmd("highlight  BlinkCmpKindText    guifg=#${scheme.base0C}")
              vim.cmd("highlight  BlinkCmpKindMethod  guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindConstructor guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindFunction guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindFolder guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindModule guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindConstant guifg=#${scheme.base09}")
              vim.cmd("highlight  BlinkCmpKindField guifg=#${scheme.base0B}")
              vim.cmd("highlight  BlinkCmpKindProperty guifg=#${scheme.base0B}")
              vim.cmd("highlight  BlinkCmpKindEnum guifg=#${scheme.base0B}")
              vim.cmd("highlight  BlinkCmpKindUnit guifg=#${scheme.base0B}")
              vim.cmd("highlight  BlinkCmpKindClass guifg=#${scheme.base0A}")
              vim.cmd("highlight  BlinkCmpKindVariable guifg=#${scheme.base0F}")
              vim.cmd("highlight  BlinkCmpKindFile guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindInterface guifg=#${scheme.base0A}")
              vim.cmd("highlight  BlinkCmpKindColor guifg=#${scheme.base08}")
              vim.cmd("highlight  BlinkCmpKindReference guifg=#${scheme.base08}")
              vim.cmd("highlight  BlinkCmpKindEnumMember guifg=#${scheme.base08}")
              vim.cmd("highlight  BlinkCmpKindStruct guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindValue guifg=#${scheme.base09}")
              vim.cmd("highlight  BlinkCmpKindEvent guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindOperator guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindTypeParameter guifg=#${scheme.base0D}")
              vim.cmd("highlight  BlinkCmpKindCopilot guifg=#${scheme.base0C}")
              vim.cmd("highlight  DapUIVariablexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DapUIModifiedValuexxx guifg=#${scheme.base09}")
              vim.cmd("highlight  DapUIThreadxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  DapUISourcexxx guifg=#${scheme.base07}")
              vim.cmd("highlight  DapUIWatchesValuexxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  DapUIBreakpointsCurrentLinexxx cterm=bold gui=bold guifg=#${scheme.base0B}")
              vim.cmd("highlight  DapUIBreakpointsDisabledLinexxx guifg=#${scheme.base04}")
              vim.cmd("highlight  DapUIStepOverxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  DapUIStepIntoxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  DapUIStepBackxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  DapUIStepOutxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  DapUIStopxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  DapUIPlayPausexxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  DapUIRestartxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  DapUIUnavailablexxx guifg=#${scheme.base03}")
              vim.cmd("highlight  NvimTreeFolderNamexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NvimTreeFolderIconxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NvimTreeNormalxxx guifg=#${scheme.base05} guibg=#${scheme.base01}")
              vim.cmd("highlight  NvimTreeOpenedFolderNamexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NvimTreeEmptyFolderNamexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NvimTreeWinSeparatorxxx guifg=#${scheme.base00} guibg=#${scheme.base00}")
              vim.cmd("highlight  NvimTreeRootFolderxxx cterm=bold gui=bold guifg=#${scheme.base07}")
              vim.cmd("highlight  NvimTreeStatuslineNcxxx guifg=#${scheme.base01} guibg=#${scheme.base01}")
              vim.cmd("highlight  DashboardHeaderxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NvimTreeGitDeletedxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  DashboardFooterxxx cterm=italic gui=italic guifg=#${scheme.base0A}")
              vim.cmd("highlight  NvimTreeImageFilexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DashboardFilesxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  DashboardKeyxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  DashboardDescxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardIconxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardHeader guifg=#${scheme.base0D}")
              vim.cmd("highlight  DashboardFooter cterm=italic gui=italic guifg=#${scheme.base0A}")
              vim.cmd("highlight  DashboardFiles guifg=#${scheme.base07}")
              vim.cmd("highlight  DashboardKey guifg=#${scheme.base09}")
              vim.cmd("highlight  DashboardDesc guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardIcon guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardMruIcon guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardMruTitle guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardFiles guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardCutIcon guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardProjectIcon guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardProjectTitleIcon guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardProjectTitle guifg=#${scheme.base0E}")
              vim.cmd("highlight  DashboardShortCut guifg=#${scheme.base0E}")
              vim.cmd("highlight  UfoFoldedFgxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  UfoFoldedEllipsisxxx guifg=#11111c guibg=#${scheme.base0D}")
              vim.cmd("highlight  RainbowDelimiterRedxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  RainbowDelimiterYellowxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  RainbowDelimiterBluexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  RainbowDelimiterOrangexxx guifg=#${scheme.base09}")
              vim.cmd("highlight  RainbowDelimiterGreenxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  RainbowDelimiterVioletxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  RainbowDelimiterCyanxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  GitSignsAddxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  GitSignsChangexxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  GitSignsDeletexxx guifg=#${scheme.base08}")
              vim.cmd("highlight  GitSignsCurrentLineBlamexxx guifg=#${scheme.base03}")
              vim.cmd("highlight  @markup.mathxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  @markup.environment.namexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  @markup.link.urlxxx cterm=underline,italic gui=underline,italic guifg=#${scheme.base06}")
              vim.cmd("highlight  @markup.rawxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  rainbow2xxx guifg=#${scheme.base09}")
              vim.cmd("highlight  @textxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  @text.titlexxx cterm=bold gui=bold guifg=#${scheme.base0D}")
              vim.cmd("highlight  rainbow3xxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  rainbow4xxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  @constructor.typescriptxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  @constructor.tsxxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  @tag.attributexxx cterm=italic gui=italic guifg=#${scheme.base0C}")
              vim.cmd("highlight  @tag.attribute.tsxxxx cterm=italic gui=italic guifg=#${scheme.base0C}")
              vim.cmd("highlight  FlashMatchxxx guifg=#${scheme.base07} guibg=#${scheme.base00}")
              vim.cmd("highlight  @string.special.symbol.rubyxxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  @type.builtin.cxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  @property.cppxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  @type.builtin.cppxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  @comment.warning.gitcommitxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  gitcommitSummaryxxx cterm=italic gui=italic guifg=#${scheme.base06}")
              vim.cmd("highlight  @fieldxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  @namespacexxx cterm=italic gui=italic guifg=#${scheme.base07}")
              vim.cmd("highlight  @text.strikexxx cterm=strikethrough gui=strikethrough guifg=#${scheme.base05}")
              vim.cmd("highlight  @text.mathxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  @text.environment.namexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  @text.literalxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  @text.todoxxx guifg=#${scheme.base00} guibg=#${scheme.base0F}")
              vim.cmd("highlight  @text.todo.checkedxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  @text.warningxxx guifg=#${scheme.base00} guibg=#${scheme.base0A}")
              vim.cmd("highlight  @text.notexxx guifg=#${scheme.base00} guibg=#${scheme.base0D}")
              vim.cmd("highlight  @text.dangerxxx guifg=#${scheme.base00} guibg=#${scheme.base08}")
              vim.cmd("highlight  diffRemovedxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  AlphaShortcutxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  AlphaHeaderxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  AlphaHeaderLabelxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  AlphaButtonsxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  AlphaFooterxxx cterm=italic gui=italic guifg=#${scheme.base0A}")
              vim.cmd("highlight  LspDiagnosticsDefaultErrorxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  LspDiagnosticsDefaultWarningxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  LspDiagnosticsDefaultHintxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  LspDiagnosticsErrorxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  LspDiagnosticsWarningxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  LspDiagnosticsHintxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  LspDiagnosticsVirtualTextErrorxxx cterm=italic gui=italic guifg=#${scheme.base08}")
              vim.cmd("highlight  LspDiagnosticsVirtualTextWarningxxx cterm=italic gui=italic guifg=#${scheme.base0A}")
              vim.cmd("highlight  LspDiagnosticsVirtualTextHintxxx cterm=italic gui=italic guifg=#${scheme.base0C}")
              vim.cmd("highlight  LspDiagnosticsUnderlineErrorxxx cterm=underline gui=underline guisp=#${scheme.base08}")
              vim.cmd("highlight  LspDiagnosticsUnderlineWarningxxx cterm=underline gui=underline guisp=#${scheme.base0A}")
              vim.cmd("highlight  LspDiagnosticsUnderlineHintxxx cterm=underline gui=underline guisp=#${scheme.base0C}")
              vim.cmd("highlight  NormalSBxxx guifg=#${scheme.base05} guibg=#11111c")
              vim.cmd("highlight  SignColumnSBxxx guifg=#${scheme.base03} guibg=#11111c")
              vim.cmd("highlight  diffOldFilexxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  diffChangedxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  illuminatedCurWordxxx guibg=#${scheme.base03}")
              vim.cmd("highlight  illuminatedWordxxx guibg=#${scheme.base03}")
              vim.cmd("highlight  debugBreakpointxxx guifg=#6c7087 guibg=#${scheme.base00}")
              vim.cmd("highlight  mkdCodeEndxxx cterm=bold gui=bold guifg=#${scheme.base0F}")
              vim.cmd("highlight  mkdCodeStartxxx cterm=bold gui=bold guifg=#${scheme.base0F}")
              vim.cmd("highlight  mkdCodeDelimiterxxx guifg=#${scheme.base05} guibg=#${scheme.base00}")
              vim.cmd("highlight  htmlH2xxx cterm=bold gui=bold guifg=#${scheme.base0D}")
              vim.cmd("highlight  qfFileNamexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  qfLineNrxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  rainbow1xxx guifg=#${scheme.base08}")
              vim.cmd("highlight  NeogitRecentcommitsxxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  rainbow6xxx guifg=#${scheme.base07}")
              vim.cmd("highlight  markdownCodexxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  markdownLinkTextxxx cterm=underline gui=underline guifg=#${scheme.base0D}")
              vim.cmd("highlight  NeogitUnpulledchangesxxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  diffIndexLinexxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  healthErrorxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  healthSuccessxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  healthWarningxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  GlyphPalette1xxx guifg=#${scheme.base08}")
              vim.cmd("highlight  GlyphPalette2xxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  GlyphPalette3xxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  @symbolxxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  csvCol7xxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  csvCol6xxx guifg=#${scheme.base07}")
              vim.cmd("highlight  csvCol5xxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  csvCol3xxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  csvCol2xxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  csvCol1xxx guifg=#${scheme.base09}")
              vim.cmd("highlight  csvCol0xxx guifg=#${scheme.base08}")
              vim.cmd("highlight  GlyphPalette9xxx guifg=#${scheme.base08}")
              vim.cmd("highlight  GlyphPalette7xxx guifg=#${scheme.base05}")
              vim.cmd("highlight  GlyphPalette6xxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  GlyphPalette4xxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  @symbol.rubyxxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  @property.typescriptxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  diffFilexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  diffNewFilexxx guifg=#${scheme.base09}")
              vim.cmd("highlight  TreesitterContextLineNumberxxx guifg=#${scheme.base03} guibg=#${scheme.base01}")
              vim.cmd("highlight  MiniJump2dSpotUniquexxx cterm=bold gui=bold guifg=#89dcec guibg=#${scheme.base00}")
              vim.cmd("highlight  MiniJump2dSpotAheadxxx guifg=#${scheme.base0C} guibg=#191927")
              vim.cmd(
                      "highlight  MiniJump2dSpotxxx cterm=bold,underline gui=bold,underline guifg=#${scheme.base09} guibg=#${scheme.base00}")
              vim.cmd("highlight  NeogitPopupActionKeyxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  NeogitFilePathxxx cterm=italic gui=italic guifg=#${scheme.base0D}")
              vim.cmd("highlight  NeogitDiffHeaderxxx cterm=bold gui=bold guifg=#${scheme.base0D} guibg=#${scheme.base00}")
              vim.cmd(
                      "highlight  NeogitDiffHeaderHighlightxxx cterm=bold gui=bold guifg=#${scheme.base09} guibg=#${scheme.base00}")
              vim.cmd("highlight  NeogitChangeModifiedxxx cterm=bold gui=bold guifg=#${scheme.base0D}")
              vim.cmd("highlight  NeogitGraphBoldGreenxxx cterm=bold gui=bold guifg=#${scheme.base0B}")
              vim.cmd("highlight  NeogitChangeUpdatedxxx cterm=bold gui=bold guifg=#${scheme.base09}")
              vim.cmd("highlight  TelescopeSelectionxxx cterm=bold gui=bold guifg=#${scheme.base05} guibg=#${scheme.base02}")
              vim.cmd("highlight  MiniDepsTitleUpdatexxx guifg=#${scheme.base00} guibg=#${scheme.base0B}")
              vim.cmd("highlight  NeogitNotificationInfoxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NeogitUnpushedToxxx cterm=bold gui=bold guifg=#${scheme.base07}")
              vim.cmd("highlight  markdownHeadingDelimiterxxx cterm=bold gui=bold guifg=#${scheme.base09}")
              vim.cmd("highlight  NeogitGraphCyanxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NeogitPopupConfigKeyxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  NeogitPopupOptionKeyxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  markdownCodeBlockxxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  NeogitChangeBothModifiedxxx cterm=bold gui=bold guifg=#${scheme.base0A}")
              vim.cmd("highlight  IblScopexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  IblIndentxxx guifg=#${scheme.base02}")
              vim.cmd("highlight  NeoTreeGitStagedxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  NeoTreeTitleBarxxx guifg=#${scheme.base01} guibg=#${scheme.base0D}")
              vim.cmd("highlight  @property.cssxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  @property.class.cssxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  @type.cssxxx guifg=#${scheme.base07}")
              vim.cmd("highlight  @type.tag.cssxxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  @string.plain.cssxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  @number.cssxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  @property.tomlxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  @label.jsonxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  @constructor.luaxxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  @property.id.cssxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  @constant.javaxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  @function.builtin.bashxxx cterm=italic gui=italic guifg=#${scheme.base08}")
              vim.cmd("highlight  @markup.list.checkedxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  FlashLabelxxx cterm=bold gui=bold guifg=#${scheme.base0B} guibg=#${scheme.base00}")
              vim.cmd("highlight  FlashCurrentxxx guifg=#${scheme.base09} guibg=#${scheme.base00}")
              vim.cmd("highlight  @string.regexxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  NvimTreeSpecialFilexxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  DashboardCenterxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  NvimTreeGitNewxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NvimTreeGitDirtyxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  DapUIWinSelectxxx guifg=#${scheme.base09}")
              vim.cmd("highlight  NeoTreeStatusLineNCxxx guifg=#${scheme.base01} guibg=#${scheme.base01}")
              vim.cmd("highlight  DapUIBreakpointsInfoxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  NeoTreeVertSplitxxx guifg=#${scheme.base00} guibg=#${scheme.base00}")
              vim.cmd("highlight  NeoTreeTabSeparatorInactivexxx guifg=#${scheme.base00} guibg=#${scheme.base00}")
              vim.cmd("highlight  NeoTreeTabSeparatorActivexxx guifg=#${scheme.base01} guibg=#${scheme.base01}")
              vim.cmd("highlight  NeoTreeTabInactivexxx guifg=#6c7087 guibg=#${scheme.base00}")
              vim.cmd("highlight  NeoTreeTabActivexxx cterm=bold gui=bold guifg=#${scheme.base07} guibg=#${scheme.base01}")
              vim.cmd("highlight  DapUITypexxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  NeoTreeGitModifiedxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  DropBarKindClassxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DropBarKindDeclarationxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  NeogitChangeRenamedxxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  DapBreakpointConditionxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  NeogitGraphBluexxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NeogitGraphBoldBluexxx cterm=bold gui=bold guifg=#${scheme.base0D}")
              vim.cmd("highlight  @comment.hintxxx guifg=#${scheme.base00} guibg=#${scheme.base0D}")
              vim.cmd("highlight  MiniDiffSignChangexxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  NeogitStashesxxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  NeogitGraphBoldYellowxxx cterm=bold gui=bold guifg=#${scheme.base0A}")
              vim.cmd("highlight  TelescopeMatchingxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NeogitChangeNewFilexxx cterm=bold gui=bold guifg=#${scheme.base0B}")
              vim.cmd("highlight  MiniDiffSignDeletexxx guifg=#${scheme.base08}")
              vim.cmd("highlight  TelescopeSelectionCaretxxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  TelescopePromptPrefix guifg=#${scheme.base0F} guibg=#FFFFFFFF")
              vim.cmd("highlight  NeogitChangeDeletedxxx cterm=bold gui=bold guifg=#${scheme.base08}")
              vim.cmd("highlight  NeogitUntrackedfilesxxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  NeogitChangeAddedxxx cterm=bold gui=bold guifg=#${scheme.base0B}")
              vim.cmd("highlight  NeogitGraphOrangexxx guifg=#${scheme.base09}")
              vim.cmd("highlight  NeogitUnmergedchangesxxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  NeogitGraphBoldPurplexxx cterm=bold gui=bold guifg=#${scheme.base07}")
              vim.cmd("highlight  NeogitDiffContextxxx guibg=#${scheme.base00}")
              vim.cmd("highlight  MiniIconsCyanxxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  MiniIconsGreenxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  MiniIconsGreyxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  MiniIconsOrangexxx guifg=#${scheme.base09}")
              vim.cmd("highlight  MiniIconsPurplexxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  MiniIconsRedxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  MiniIconsYellowxxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  MiniIndentscopeSymbolxxx guifg=#${scheme.base05}")
              vim.cmd("highlight  NeogitBranchxxx cterm=bold gui=bold guifg=#${scheme.base09}")
              vim.cmd("highlight  NeogitRemotexxx cterm=bold gui=bold guifg=#${scheme.base0B}")
              vim.cmd("highlight  TreesitterContextBottomxxx cterm=underline gui=underline guisp=#${scheme.base02}")
              vim.cmd("highlight  NeogitHunkHeaderHighlightxxx guifg=#${scheme.base0D} guibg=#353e5b")
              vim.cmd("highlight  NeogitDiffContextHighlightxxx guibg=#${scheme.base02}")
              vim.cmd("highlight  lualine_b_inactive gui=bold guifg=#${scheme.base03} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_c_inactive guifg=#6c7087 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_a_inactive guifg=#${scheme.base0D} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_b_normal guifg=#${scheme.base0D} guibg=#${scheme.base02}")
              vim.cmd("highlight  lualine_c_normal guifg=#${scheme.base05} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_a_normal gui=bold guifg=#${scheme.base01} guibg=#${scheme.base0D}")
              vim.cmd("highlight  lualine_b_replace guifg=#${scheme.base08} guibg=#${scheme.base02}")
              vim.cmd("highlight  lualine_a_replace gui=bold guifg=#${scheme.base00} guibg=#${scheme.base08}")
              vim.cmd("highlight  lualine_b_command guifg=#${scheme.base09} guibg=#${scheme.base02}")
              vim.cmd("highlight  lualine_a_command gui=bold guifg=#${scheme.base00} guibg=#${scheme.base09}")
              vim.cmd("highlight  lualine_b_visual guifg=#${scheme.base0E} guibg=#${scheme.base02}")
              vim.cmd("highlight  lualine_a_visual gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0E}")
              vim.cmd("highlight  lualine_b_terminal guifg=#${scheme.base0B} guibg=#${scheme.base02}")
              vim.cmd("highlight  lualine_a_terminal gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0B}")
              vim.cmd("highlight  lualine_b_insert guifg=#${scheme.base0B} guibg=#${scheme.base02}")
              vim.cmd("highlight  lualine_a_insert gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0B}")
              vim.cmd("highlight  lualine_x_diff_added_normal guifg=#${scheme.base0B} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_added_insert guifg=#${scheme.base0B} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_added_visual guifg=#${scheme.base0B} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_added_replace guifg=#${scheme.base0B} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_added_command guifg=#${scheme.base0B} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_added_terminal guifg=#${scheme.base0B} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_added_inactive guifg=#${scheme.base0B} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_modified_normal guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_modified_insert guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_modified_visual guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_modified_replace guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_modified_command guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_modified_terminal guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_modified_inactive guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_removed_normal guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_removed_insert guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_removed_visual guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_removed_replace guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_removed_command guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_removed_terminal guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_diff_removed_inactive guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  DiffviewSecondaryxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  DiffviewPrimaryxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  DiffviewFilePanelCounterxxx cterm=bold gui=bold guifg=#${scheme.base0F}")
              vim.cmd("highlight  DiffviewFilePanelFileNamexxx guifg=#${scheme.base05}")
              vim.cmd("highlight  DapUIPlayPauseNCxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  DapUIRestartNCxxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  DapUIStopNCxxx guifg=#${scheme.base08}")
              vim.cmd("highlight  DapUIUnavailableNCxxx guifg=#${scheme.base03}")
              vim.cmd("highlight  DapUIStepOverNCxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  DapUIStepIntoNCxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  DapUIStepBackNCxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  DapUIStepOutNCxxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  BufferDefaultCurrentxxx ctermfg=255 guifg=#${scheme.base0B}")
              vim.cmd("highlight  BufferDefaultCurrentADDEDxxx ctermfg=82 guifg=#${scheme.base0B}")
              vim.cmd("highlight  BufferDefaultCurrentCHANGEDxxx ctermfg=75 guifg=#${scheme.base0A}")
              vim.cmd("highlight  BufferDefaultCurrentDELETEDxxx ctermfg=124 guifg=#${scheme.base08}")
              vim.cmd("highlight  BufferDefaultCurrentERRORxxx ctermfg=124 guifg=#${scheme.base08}")
              vim.cmd("highlight  BufferDefaultCurrentHINTxxx ctermfg=168 guifg=#${scheme.base0C}")
              vim.cmd("highlight  BufferDefaultCurrentModxxx ctermfg=178 guifg=#${scheme.base0A}")
              vim.cmd("highlight  BufferDefaultCurrentWARNxxx ctermfg=208 guifg=#${scheme.base0A}")
              vim.cmd("highlight  BufferDefaultInactivexxx ctermfg=255 guifg=#${scheme.base03} guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultInactiveADDEDxxx ctermfg=82 guifg=#${scheme.base0B} guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultInactiveCHANGEDxxx ctermfg=75 guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultInactiveDELETEDxxx ctermfg=124 guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultInactiveERRORxxx ctermfg=124 guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultInactiveHINTxxx ctermfg=168 guifg=#${scheme.base0C} guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultInactiveIndexxxx ctermfg=240 guifg=#6c7087 guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultInactiveINFOxxx ctermfg=217 guifg=#89dcec guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultInactiveModxxx ctermfg=178 guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultInactiveSignxxx ctermfg=240 guifg=#6c7087 guibg=#${scheme.base01}")
              vim.cmd(
              "highlight  BufferDefaultInactiveTargetxxx cterm=bold ctermfg=9 gui=bold guifg=Red guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultInactiveWARNxxx ctermfg=208 guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd(
                      "highlight  BufferDefaultTabpagesSepxxx cterm=bold ctermfg=255 gui=bold guifg=#9399b3 guibg=#${scheme.base01}")
              vim.cmd("highlight  BufferDefaultTabpageFillxxx ctermfg=102 guifg=#${scheme.base05} guibg=#${scheme.base01}")
              vim.cmd(
                      "highlight  BufferDefaultTabpagesxxx cterm=bold ctermfg=75 gui=bold guifg=#${scheme.base09} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceFormatProgressDonexxx guifg=#${scheme.base05} guibg=#3e5768")
              vim.cmd("highlight  lualine_x_filetype_DevIconDefault_normalxxx guifg=#6d8086 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconDefault_insertxxx guifg=#6d8086 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconDefault_visualxxx guifg=#6d8086 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconDefault_replacexxx guifg=#6d8086 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconDefault_commandxxx guifg=#6d8086 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconDefault_terminalxxx guifg=#6d8086 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconDefault_inactivexxx guifg=#6d8086 guibg=#${scheme.base01}")
              vim.cmd(
                      "highlight  lualine_transitional_lualine_a_normal_to_lualine_b_normalxxx guifg=#${scheme.base0D} guibg=#${scheme.base02}")
              vim.cmd(
                      "highlight  lualine_transitional_lualine_b_normal_to_lualine_c_normalxxx guifg=#${scheme.base02} guibg=#${scheme.base01}")
              vim.cmd("highlight  DevIconDefaultInactivexxx ctermfg=66 guifg=#6d8086 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconNix_normalxxx guifg=#7ebae4 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconNix_insertxxx guifg=#7ebae4 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconNix_visualxxx guifg=#7ebae4 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconNix_replacexxx guifg=#7ebae4 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconNix_commandxxx guifg=#7ebae4 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconNix_terminalxxx guifg=#7ebae4 guibg=#${scheme.base01}")
              vim.cmd("highlight  lualine_x_filetype_DevIconNix_inactivexxx guifg=#7ebae4 guibg=#${scheme.base01}")
              vim.cmd(
                      "highlight  lualine_transitional_lualine_a_command_to_lualine_b_commandxxx guifg=#${scheme.base09} guibg=#${scheme.base02}")
              vim.cmd(
                      "highlight  lualine_transitional_lualine_b_command_to_lualine_c_normalxxx guifg=#${scheme.base02} guibg=#${scheme.base01}")
              vim.cmd("highlight  DevIconNixInactivexxx ctermfg=110 guifg=#7ebae4 guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr74xxx cterm=bold,italic gui=bold,italic guifg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr54xxx guifg=#${scheme.base0E}")
              vim.cmd("highlight  NoiceAttr55xxx cterm=italic gui=italic guifg=#${scheme.base0A}")
              vim.cmd("highlight  NoiceAttr56xxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr57xxx cterm=italic gui=italic guifg=#${scheme.base04}")
              vim.cmd("highlight  NoiceAttr58xxx guifg=#${scheme.base05}")
              vim.cmd("highlight  NoiceAttr60xxx guifg=#${scheme.base0F}")
              vim.cmd("highlight  NoiceAttr61xxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr62xxx guifg=#bac2df guibg=#${scheme.base03}")
              vim.cmd("highlight  NoiceAttr63xxx guifg=#${scheme.base05} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr64xxx guifg=#${scheme.base0D} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr65xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base09}")
              vim.cmd("highlight  NoiceAttr66xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr67xxx cterm=bold gui=bold guifg=#${scheme.base01} guibg=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr68xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0C}")
              vim.cmd("highlight  NoiceAttr69xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr70xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0E}")
              vim.cmd("highlight  NoiceAttr71xxx guifg=#${scheme.base03} guibg=#f5c2e8")
              vim.cmd(
                      "highlight  NoiceAttr72xxx cterm=bold,underline,italic gui=bold,underline,italic guifg=#${scheme.base05} guibg=#${scheme.base00} guisp=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr73xxx guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr75xxx guifg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr76xxx guifg=#${scheme.base03} guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr77xxx cterm=bold gui=bold guifg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr78xxx cterm=bold gui=bold guifg=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr79xxx guibg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr80xxx guifg=#${scheme.base07}")
              vim.cmd("highlight  NoiceAttr81xxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  NoiceAttr82xxx guifg=#${scheme.base09}")
              vim.cmd("highlight  NoiceAttr84xxx guifg=#${scheme.base00} guibg=#${scheme.base0A}")
              vim.cmd("highlight  NoiceAttr85xxx guifg=#${scheme.base00} guibg=#${scheme.base0F}")
              vim.cmd("highlight  NoiceAttr87xxx cterm=bold gui=bold guibg=#${scheme.base03}")
              vim.cmd("highlight  NoiceAttr88xxx guifg=#${scheme.base01} guibg=#7ec9d9")
              vim.cmd("highlight  NoiceAttr89xxx cterm=undercurl gui=undercurl guisp=#${scheme.base0A}")
              vim.cmd("highlight  NoiceAttr90xxx cterm=undercurl gui=undercurl guisp=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr91xxx guifg=#${scheme.base03} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr92xxx cterm=bold gui=bold guifg=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr96xxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  NoiceAttr97xxx cterm=bold gui=bold guifg=#${scheme.base0E}")
              vim.cmd("highlight  NoiceAttr98xxx guifg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr99xxx guifg=#${scheme.base00} guibg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr102xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0A}")
              vim.cmd("highlight  NoiceAttr103xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#89dcec")
              vim.cmd("highlight  NoiceAttr107xxx cterm=bold gui=bold guifg=#${scheme.base05}")
              vim.cmd("highlight  NoiceAttr110xxx guifg=#${scheme.base00} guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr111xxx guifg=#${scheme.base04}")
              vim.cmd("highlight  NoiceAttr112xxx guifg=#${scheme.base03}")
              vim.cmd("highlight  NoiceAttr113xxx cterm=bold gui=bold guifg=#${scheme.base07}")
              vim.cmd("highlight  NoiceAttr114xxx guifg=#${scheme.base01} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr116xxx guifg=#11111c guibg=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr117xxx guifg=#${scheme.base05}")
              vim.cmd("highlight  NoiceAttr119xxx cterm=underline,italic gui=underline,italic guifg=#${scheme.base06}")
              vim.cmd("highlight  NoiceAttr120xxx cterm=italic gui=italic guifg=#${scheme.base0C}")
              vim.cmd("highlight  NoiceAttr121xxx guifg=#${scheme.base07} guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr122xxx cterm=italic gui=italic guifg=#${scheme.base06}")
              vim.cmd("highlight  NoiceAttr123xxx cterm=italic gui=italic guifg=#${scheme.base07}")
              vim.cmd("highlight  NoiceAttr125xxx guifg=#${scheme.base00} guibg=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr126xxx guibg=#${scheme.base03}")
              vim.cmd("highlight  NoiceAttr127xxx cterm=italic gui=italic guifg=#${scheme.base08} guibg=#32283b")
              vim.cmd("highlight  NoiceAttr128xxx cterm=italic gui=italic guifg=#${scheme.base0A} guibg=#33313b")
              vim.cmd("highlight  NoiceAttr130xxx cterm=italic gui=italic guifg=#${scheme.base0C} guibg=#29313f")
              vim.cmd("highlight  NoiceAttr131xxx cterm=italic gui=italic guifg=#${scheme.base0B} guibg=#29313f")
              vim.cmd("highlight  NoiceAttr132xxx cterm=italic gui=italic guifg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr133xxx cterm=italic gui=italic guifg=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr134xxx cterm=underline gui=underline guisp=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr135xxx cterm=underline gui=underline guisp=#${scheme.base0A}")
              vim.cmd("highlight  NoiceAttr137xxx cterm=underline gui=underline guisp=#${scheme.base0C}")
              vim.cmd("highlight  NoiceAttr138xxx cterm=underline gui=underline guisp=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr142xxx guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr143xxx guifg=#${scheme.base00} guibg=#${scheme.base05}")
              vim.cmd("highlight  NoiceAttr144xxx guibg=#${scheme.base02}")
              vim.cmd("highlight  NoiceAttr146xxx guifg=#${scheme.base06}")
              vim.cmd("highlight  NoiceAttr147xxx guifg=#${scheme.base0B} guibg=#${scheme.base03}")
              vim.cmd("highlight  NoiceAttr148xxx cterm=undercurl gui=undercurl guisp=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr149xxx cterm=undercurl gui=undercurl guisp=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr150xxx guifg=#${scheme.base01} guibg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr151xxx guifg=#${scheme.base05} guibg=#3e5768")
              vim.cmd("highlight  NoiceAttr154xxx guifg=#${scheme.base05} guibg=#11111c")
              vim.cmd("highlight  NoiceAttr155xxx guifg=#${scheme.base05} guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr156xxx cterm=bold gui=bold guifg=#${scheme.base09} guibg=#${scheme.base03}")
              vim.cmd("highlight  NoiceAttr157xxx guifg=#f5c2e8 guibg=#${scheme.base03}")
              vim.cmd("highlight  NoiceAttr158xxx guifg=#${scheme.base03} guibg=#11111c")
              vim.cmd("highlight  NoiceAttr159xxx guifg=#${scheme.base0D} guibg=#${scheme.base03}")
              vim.cmd("highlight  NoiceAttr160xxx guifg=#6c7087 guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr162xxx cterm=bold gui=bold guifg=#${scheme.base0F}")
              vim.cmd("highlight  NoiceAttr163xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0F}")
              vim.cmd("highlight  NoiceAttr164xxx cterm=underline gui=underline guifg=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr165xxx cterm=italic gui=italic guifg=#${scheme.base0E}")
              vim.cmd("highlight  NoiceAttr172xxx cterm=bold gui=bold guifg=#89dcec guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr173xxx guifg=#${scheme.base0C} guibg=#191927")
              vim.cmd(
                      "highlight  NoiceAttr174xxx cterm=bold,underline gui=bold,underline guifg=#${scheme.base09} guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr175xxx cterm=italic gui=italic guifg=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr176xxx cterm=bold gui=bold guifg=#${scheme.base0D} guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr177xxx cterm=bold gui=bold guifg=#${scheme.base09} guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr178xxx cterm=bold gui=bold guifg=#${scheme.base09}")
              vim.cmd("highlight  NoiceAttr179xxx cterm=bold gui=bold guifg=#${scheme.base05} guibg=#${scheme.base02}")
              vim.cmd("highlight  NoiceAttr180xxx guifg=#${scheme.base00} guibg=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr181xxx cterm=bold gui=bold guifg=#${scheme.base0A}")
              vim.cmd("highlight  NoiceAttr182xxx guifg=#${scheme.base02}")
              vim.cmd("highlight  NoiceAttr183xxx guifg=#${scheme.base01} guibg=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr184xxx cterm=bold gui=bold guifg=#${scheme.base0B} guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr185xxx guifg=#${scheme.base09} guibg=#${scheme.base00}")
              vim.cmd("highlight  NoiceAttr186xxx cterm=bold gui=bold guifg=#${scheme.base07} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr191xxx cterm=underline gui=underline guisp=#${scheme.base02}")
              vim.cmd("highlight  NoiceAttr193xxx guifg=#${scheme.base0D} guibg=#353e5b")
              vim.cmd("highlight  NoiceAttr437xxx cterm=bold,underline gui=bold,underline guisp=#${scheme.base05}")
              vim.cmd("highlight  NoiceAttr439xxx cterm=bold gui=bold guifg=#${scheme.base03} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr440xxx guifg=#6c7087 guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr441xxx guifg=#${scheme.base0D} guibg=#${scheme.base02}")
              vim.cmd("highlight  NoiceAttr442xxx cterm=bold gui=bold guifg=#${scheme.base01} guibg=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr443xxx guifg=#${scheme.base08} guibg=#${scheme.base02}")
              vim.cmd("highlight  NoiceAttr444xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr445xxx guifg=#${scheme.base09} guibg=#${scheme.base02}")
              vim.cmd("highlight  NoiceAttr446xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base09}")
              vim.cmd("highlight  NoiceAttr447xxx guifg=#${scheme.base0E} guibg=#${scheme.base02}")
              vim.cmd("highlight  NoiceAttr448xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0E}")
              vim.cmd("highlight  NoiceAttr449xxx guifg=#${scheme.base0B} guibg=#${scheme.base02}")
              vim.cmd("highlight  NoiceAttr450xxx cterm=bold gui=bold guifg=#${scheme.base00} guibg=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr451xxx guifg=#${scheme.base0B} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr452xxx guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr453xxx guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr470xxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr472xxx guifg=#${scheme.base0D}")
              vim.cmd("highlight  NoiceAttr473xxx cterm=bold gui=bold guifg=#${scheme.base0F}")
              vim.cmd("highlight  NoiceAttr474xxx guifg=#${scheme.base05}")
              vim.cmd("highlight  NoiceAttr480xxx guifg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr481xxx guifg=#${scheme.base03}")
              vim.cmd("highlight  NoiceAttr482xxx cterm=bold gui=bold guifg=#${scheme.base09} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr483xxx guifg=#${scheme.base05} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr484xxx cterm=bold gui=bold guifg=#9399b3 guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr495xxx guifg=#${scheme.base03} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr496xxx guifg=#${scheme.base0B} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr497xxx guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr498xxx guifg=#${scheme.base08} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr499xxx guifg=#${scheme.base0C} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr500xxx guifg=#6c7087 guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr501xxx guifg=#89dcec guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr502xxx guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr503xxx guifg=#${scheme.base0A} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr504xxx cterm=bold gui=bold guifg=#ff0000 guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr505xxx guifg=#${scheme.base05} guibg=#3e5768")
              vim.cmd("highlight  NoiceAttr507xxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr508xxx guifg=#${scheme.base0B}")
              vim.cmd("highlight  NoiceAttr509xxx guifg=#${scheme.base08}")
              vim.cmd("highlight  NoiceAttr510xxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  NoiceAttr512xxx guifg=#${scheme.base0C}")
              vim.cmd("highlight  NoiceAttr514xxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  NoiceAttr516xxx guifg=#${scheme.base0A}")
              vim.cmd("highlight  NoiceAttr520xxx guifg=#6d8086 guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr521xxx guifg=#${scheme.base02} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr522xxx guifg=#6d8086 guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr528xxx guifg=#7ebae4 guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr535xxx guifg=#7ebae4 guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr818xxx cterm=bold,underline gui=bold,underline guisp=#${scheme.base05}")
              vim.cmd("highlight  NoiceAttr819xxx cterm=bold gui=bold guifg=#${scheme.base03} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr835xxx cterm=bold gui=bold guifg=#${scheme.base09} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr836xxx cterm=bold gui=bold guifg=#9399b3 guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr837xxx guifg=#${scheme.base0C} guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr838xxx guifg=#89dcec guibg=#${scheme.base01}")
              vim.cmd("highlight  NoiceAttr839xxx cterm=bold gui=bold guifg=#ff0000 guibg=#${scheme.base01}")
      
              vim.cmd("highlight  BufferDefaultCurrent  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentADDED  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentERROR guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentCHANGED  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentDELETED  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentINFO  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentHINT  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentIndex  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentPin  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentSign  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentWarn  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentTarget  guibg=nil")
              vim.cmd("highlight  BufferDefaultCurrentMod  guibg=nil")
      
              vim.cmd("highlight  Pmenu  guibg=nil")
              vim.cmd("highlight  NormalFloat  guibg=nil")
      
              vim.cmd("highlight  NeoTreeDirectoryIcon  guifg=#${scheme.base0D}")
              vim.cmd("highlight  NeoTreeDirectoryName  guifg=#${scheme.base0D}")
      
              vim.cmd("highlight  NeoTreeNormal  guifg=#${scheme.base05} guibg=#${scheme.base01}")
              vim.cmd("highlight  NeoTreeNormalNC  guifg=#${scheme.base05} guibg=#${scheme.base01}")
              vim.cmd("highlight  NeoTreeExpander  guifg=#" .. overlay0)
              vim.cmd("highlight  NeoTreeIndentMarker  guifg=#" .. overlay0)
              vim.cmd("highlight  NeoTreeRootName cterm=bold gui=bold guifg=#${scheme.base0D}")
              vim.cmd("highlight  NeoTreeSymbolicLinkTarget  guifg=#${scheme.base0F}")
              vim.cmd("highlight  NeoTreeModified  guifg=#${scheme.base09}")
      
              vim.cmd("highlight  NeoTreeGitAdded  guifg=#${scheme.base0B}")
              vim.cmd("highlight  NeoTreeGitConflict  guifg=#${scheme.base08}")
              vim.cmd("highlight  NeoTreeGitDeleted  guifg=#${scheme.base08}")
              vim.cmd("highlight  NeoTreeGitIgnored  guifg=#${scheme.base02}")
              vim.cmd("highlight  NeoTreeGitModified  guifg=#${scheme.base0A}")
              vim.cmd("highlight  NeoTreeGitUnstaged  guifg=#${scheme.base08}")
              vim.cmd("highlight  NeoTreeGitUntracked  guifg=#${scheme.base0E}")
              vim.cmd("highlight  NeoTreeGitStaged  guifg=#${scheme.base0B}")
      
              vim.cmd("highlight!  link NeoTreeFloatBorder  FloatBorder")
              vim.cmd("highlight!  link NeoTreeFloatTitle  FloatTitle")
              vim.cmd("highlight  NeoTreeTitleBar  guifg=#${scheme.base01}  guibg=#${scheme.base0D}")
      
              vim.cmd("highlight  NeoTreeFileNameOpened  guifg=#${scheme.base0F}")
              vim.cmd("highlight  NeoTreeDimText  guifg=#" .. overlay1)
              vim.cmd("highlight  NeoTreeFilterTerm cterm=bold gui=bold guifg=#${scheme.base0B}")
              vim.cmd("highlight  NeoTreeTabActive cterm=bold gui=bold guifg=#${scheme.base07}  guibg=#${scheme.base00}")
              vim.cmd("highlight  NeoTreeTabInactive  guifg=#${scheme.base07}  guibg=#" .. overlay0)
              vim.cmd("highlight!  link NeoTreeTabSeparatorActive  FloatBorder")
              vim.cmd("highlight!  link NeoTreeTabSeparatorInactive FloatBorder")
              vim.cmd("highlight  NeoTreeVertSplit  guifg=#${scheme.base00}  guibg=#${scheme.base00}")
              vim.cmd("highlight  NeoTreeWinSeparator  guifg=#${scheme.base00}  guibg=#${scheme.base00}")
              vim.cmd("highlight  NeoTreeCursorLine  guibg=#${scheme.base02}")
              vim.cmd("highlight  NeoTreeStatusLineNC  guifg=#" .. mantle .. "guibg=#" .. mantle)
      
              vim.cmd("highlight!  link WinSeparator  FloatBorder")
              vim.cmd("highlight!  link TelescopeBorder  FloatBorder")
              vim.cmd("highlight!  link TelescopePromptBorder  FloatBorder")
              vim.cmd("highlight!  link TelescopeNormal  FloatBorder")
              vim.cmd("highlight!  link TelescopePromptNormal  FloatBorder")
              vim.cmd("highlight!  link TelescopePromptTitle  FloatBorder")
              vim.cmd("highlight!  link TelescopePreviewTitle  FloatBorder")
              vim.cmd("highlight!  link TelescopeResultsTitle  FloatBorder")
              vim.cmd("highlight!  link NoiceCmdlinePopupBorder  FloatBorder")
              vim.cmd("highlight  FloatBorder  guifg=#${scheme.base0D} guibg=nil")
              vim.cmd("highlight  Border  guifg=#${scheme.base0D} guibg=nil")
              vim.cmd("highlight  FloatBorder  guifg=#${scheme.base0D} guibg=nil")
      
              vim.cmd("highlight  NonText guifg=#" .. change_color("${scheme.base03}", 40))
              vim.cmd("highlight  Comment guifg=#" .. change_color("${scheme.base03}", 40))
              vim.cmd("highlight  TSComment guifg=#" .. change_color("${scheme.base03}", 40))
              vim.cmd("highlight  LspInlayHint guifg=#" .. change_color("${scheme.base03}", 40))
              vim.cmd("highlight!  link CmpGhostText  Comment")
      
              vim.cmd("highlight  GitGutterChange  guifg=#${scheme.base0A}")
              vim.cmd("highlight  GitGutterAdd  guifg=#${scheme.base0B}")
              vim.cmd("highlight  GitGutterDelete  guifg=#${scheme.base08}")
              vim.cmd("highlight  GitGutterChangeDelete  guifg=#${scheme.base07}")
              vim.cmd("highlight  GitSignsStagedChange        guifg=#" .. change_color("${scheme.base0A}", -60))
              vim.cmd("highlight  GitSignsStagedAdd           guifg=#" .. change_color("${scheme.base0B}", -60))
              vim.cmd("highlight  GitSignsStagedDelete        guifg=#" .. change_color("${scheme.base08}", -60))
              vim.cmd("highlight  GitSignsStagedChangeDelete  guifg=#" .. change_color("${scheme.base07}", -60))
      
      
      
              --vim.cmd("highlight  Identifier  guifg=#${scheme.base0D}")
              --vim.cmd("highlight  String  guifg=#${scheme.base0B}")
              --vim.cmd("highlight  Character  guifg=#${scheme.base0B}")
              --vim.cmd("highlight  Number  guifg=#${scheme.base08}")
              --vim.cmd("highlight  Boolean  guifg=#${scheme.base08}")
              --vim.cmd("highlight  Float  guifg=#${scheme.base08}")
              --vim.cmd("highlight  Function  guifg=#${scheme.base0D}")
              --vim.cmd("highlight  Conditional  guifg=#${scheme.base0C}")
              --vim.cmd("highlight  Repeat  guifg=#${scheme.base0D}")
              --vim.cmd("highlight  Label  guifg=#${scheme.base0D}")
              --vim.cmd("highlight  Operator  guifg=#${scheme.base09}")
              --vim.cmd("highlight  Keyword  guifg=#${scheme.base08}")
              --vim.cmd("highlight  Exception  guifg=#${scheme.base08}")
              --vim.cmd("highlight  Include  guifg=#${scheme.base0C}")
              --vim.cmd("highlight  Define  guifg=#${scheme.base0A}")
              --vim.cmd("highlight  Macro  guifg=#${scheme.base0A}")
              --vim.cmd("highlight  PreCondit  guifg=#${scheme.base0A}")
              --vim.cmd("highlight  StorageClass  guifg=#${scheme.base07}")
              --vim.cmd("highlight  Structure  guifg=#${scheme.base07}")
              --vim.cmd("highlight  Typedef  guifg=#${scheme.base07}")
              --vim.cmd("highlight  Tag  guifg=#${scheme.base0D}")
              --vim.cmd("highlight  SpecialChar  guifg=#${scheme.base08}")
              --vim.cmd("highlight  Delimiter  guifg=#${scheme.base0F}")
              --vim.cmd("highlight  SpecialComment  guifg=#${scheme.base06}")
              --vim.cmd("highlight  Debug  guifg=#${scheme.base06}")
      end
      vim.api.nvim_create_autocmd('VimEnter', {
        group = vim.api.nvim_create_augroup('theme', { clear = true }),
        callback = function()
          fix_theme()
        end,
      })
'';
};
}
